### ISSUE TITLE
How to visualize bam files ?

### ISSUE THREAD

**Issue by bnouyou** [broadinstitute/seqr#1383]
Hello,
I have installed the latest version with Docker, and I would like to visualize the bam files. 
It worked before, when I use the previous version. 
But now it's not working. I have done exactly what I did before : a TSV file with SampleIDs and Paths. When I import this TSV file, I have this error on screen : "Error updating SAMPLE-1: Error accessing "/input_bams/SAMPLE-1.bam"
The link to ReadViz Setup Instructions does not work , so I can't check if my settings are correct.

About the path, I am wondering if I can use a symlink (my bam files are not stored in the same place than the Seqr instance) ?

Thank you in advance for your help.

**Comment by hanars** [comment]
You cannot use symlinks, it must be a valid absolute path that is recognizable to python (i.e. if you open up a python shell and run `open(path)` it needs to succeed

**Comment by bnouyou** [comment]
How can I do if my bam files are not in the same server than the seqr instance ? 
My seqr instance is running on a VM and the bam files are on another server. 
I have mounted volumes on the docker-compose files to access to the folder where are the bam files. But even if I put this path in the TSV file for importing bam files, I have an error when I import the TSV file.

**Comment by hanars** [comment]
I'm sorry but this is no longer a supported use case. You can either store your files in google cloud or on the same server as seqr

**Comment by bnouyou** [comment]
I have also tried to put some bam files on the same server than seqr, and it still doesn't work. About the abosolut path, should it be the path for Docker (ex : /input_bams) or should it be the entire path in my serveur ?

**Comment by hanars** [comment]
from the server, its should be an absolute path. So if you open a python shell on the server the path you provide needs to be valid for pythons `open()`

**Comment by bnouyou** [comment]
It works when I do `open(path)` in python. Where `path` is the absolute path of the file in my server.
But I still have this error message.
I am wondering if the path is correct because Seqr is running with docker, and inside this docker container this path is not recognized.
For example, the path in my serveur is `/wes/data/input_bams/SAMPLE1.bam`
But in the Docker, I have mounted it as `/input_bams/SAMPLE1.bam`

**Comment by bnouyou** [comment]
Maybe I can try to add the bam file using the Django Admin interface. I have seen I can put the file path there.
I have put the absolute path (not symlink), but when I zomm on the read in the IGV viewer, at the a=end I have "Error loading data". So I suppose there is an issue with the path.

**Comment by hanars** [comment]
seqr validates the path when you add it. If it won't let you add the path, its because it won't work. Bypassing the system to add it will never work in IGV, you need to have the file accessible and defined in a way seqr can access it, which as I explained above is a valid path for python to open relative to the server you have running. When you are calling `open(path)` in python to test it, are you doing it from inside the docker image, or from your own machine? Because the path you add to seqr needs to be the one that works within docker

**Comment by bnouyou** [comment]
Hello,
I do the `open(path)` in the docker image. And it works, the file is found.
In the docker-compose.yml, I have added a volume `input_bams`. This folder is a symlink to a folder which contains the bam files. I have done the same thing for the folder `input_vcfs` where I have put the vcf files, and this works.

**Comment by hanars** [comment]
I'm really glad you got this working!

**Comment by bnouyou** [comment]
No it's not working. Sorry for my message, it was not very clear.
It works in python. The file is found.
But when I import the tsv file with bam paths, it still not work.

**Comment by bnouyou** [comment]
Could it be a problem with "rights" for accessing the bam file from seqr ?

**Comment by hanars** [comment]
No my guess is that symlinks work differently in python, you need `os.path.isfile` to be passing for validation as well as `open`. From the docker image, is that working? Also, maybe try changing relative and absolute paths in the tsv

**Comment by bnouyou** [comment]
I have tried the python command `os.path.isfile` from the docker image and it was working (result `True`) with and without symlink (I have tested both cases : symlink for bam files in another server, and bam files in the same server so with no symlink).

So then I have tried these paths in the TSV file, and it still not work. I have the same message "error accessing file...".

**Comment by bnouyou** [comment]
How can I see the full stack trace of the error ?

**Comment by hanars** [comment]
It should print to the logs

**Comment by bnouyou** [comment]
This is what I have in logs in the docker container when I try to upload a tsv file with the bam file path for one sample:

```
seqr_1             | 172.18.8.26 - - [13/Aug/2020:08:11:44 +0000] "POST /api/individual/I0000006_sample001/update_igv_sample HTTP/1.1" 400 85 "http://lx165/project/R0001_test/project_page" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0"
```

So I see there is error 400, but I don't understand why.
I don't know how can I have more information about the issue.

The bam file is found in python with no problem. The problem is only in Seqr.

**Comment by hanars** [comment]
The only other thing I can think of is if the file is getting parsed in a malformed way and theres trailing whitespace or newlines or something on the file name. Can you try uploading it in a different file format?

**Comment by bnouyou** [comment]
I have just tried xls format and it's worse : this time I have directly this message `File contains no valid workbook part` when I have selected the file. I haven't click on 'Submit' button.

**Comment by hanars** [comment]
what about csv?

**Comment by bnouyou** [comment]
It's possible to use csv ? It's not specified in the submission form.

**Comment by hanars** [comment]
yes, it supports xls, tsv, csv, and json (although I'm not 100% sure json works)

**Comment by bnouyou** [comment]
Ok! I will test and I will let you know which works.

**Comment by bnouyou** [comment]
Even in CSV, it's still not work. I have the same error `Error updating SAMPLE-1: Error accessing "/input_vcfs/EXOME-1/SAMPLE-1.bam" `

**Comment by hanars** [comment]
But `os.path.isfile("/input_vcfs/EXOME-1/SAMPLE-1.bam")` return True? @bw any ideas why this would happen

**Comment by bnouyou** [comment]
Yes `os.path.isfile("/input_vcfs/EXOME-1/SAMPLE-1.bam")` returns true.

**Comment by bw2** [comment]
Sorry, just back from vacation. I don't have any immediate ideas, but just to double-check, you mentioned that the bams are in `/input_bams`, and you are using `/input_vcfs` in your tests above - is that intentional? Also, when you say you're running the os.path.isfile check inside docker and it returns True, are you doing that with a command like
 
```
docker-compose exec seqr python -c "import os; print(os.path.isfile('/input_vcfs/EXOME-1/SAMPLE-1.bam')"
```
?

**Comment by bnouyou** [comment]
Hello,
Actually I have tried both folders. I have put the bams files in both folders for testing.

And about the python command, I tested it directly in python, not with this exact command.
O just tested the command you wrote here, and I have this message:

```
docker-compose exec seqr python -c "import os; print(os.path.isfile('/input_vcfs/EXOME-1/SAMPLE-1.bam')"
  File "<string>", line 1
    import os; print(os.path.isfile('/input_vcfs/EXOME-1/SAMPLE-1.bam')
                                                                                    ^
SyntaxError: unexpected EOF while parsing
```
Whereas if I open a python terminal and write the python command, it returns True.

**Comment by bw2** [comment]
I just want to double check that we're running it in the same environment. 
I forgot the last paren': 
```
docker-compose exec seqr python -c "import os; print(os.path.isfile('/input_vcfs/EXOME-1/SAMPLE-1.bam'))"
```

**Comment by bnouyou** [comment]
Ah yes it misses one parenthese.
This command returns False..

So I understand why I have this error when I imported the TSV file with the path. But what I don't understand is how I can solve this issue.

**Comment by bw2** [comment]
Ok, great. If you run 
```
docker-compose exec seqr /bin/bash
```
it will open a bash shell inside the seqr docker container. You can use `cd` and `ls` to explore the directory structure. 
In this shell, if you do 
```
cd /input_vcfs/
cd EXOME-1/
ls -l 
```
you should see your SAMPLE-1.bam and SAMPLE-1.bam.bai with the correct file size.

**Comment by bnouyou** [comment]
Oh I think I know why. I have mounted the `/input_bams` and `/input_vcfs` folders in the pipeline-runner container and not in the seqr container. 
That's why in the seqr container I don't see these folders and so I don't see the files. I will try to mount the folders in seqr containers, I suppose it will work.

**Comment by bw2** [comment]
Yes that makes sense. We need to update/add better docs and mount points for this use case.

**Comment by bnouyou** [comment]
Hello,
So I have stopped the containers, added the volume in the docker-compose.yml for seqr container, and started the docker containers.
But now I have a problem, in the Seqr web interface I see that there is no project, and if I go in the admin interface, I have this issue:

![image](https://user-images.githubusercontent.com/22322228/91604041-45815680-e96e-11ea-9645-a56030da3e55.png)

Do you have an idea about what is wrong this time ?

**Comment by hanars** [comment]
It looks like the code you have running is out of sync with the database you have running. The code you have expects a `phenotips_patient_id` column which was removed in June and is apparently not present in your database. I would recommend pulling the latest version of the seqr code

**Comment by bnouyou** [comment]
Hello,
I have pulled the latest version of Seqr, and I still have an issue:
`column seqr_individual.sv_flags does not exist`

Do you have an idea about this problem ?

**Comment by bnouyou** [comment]
And in the logs in the terminal, I see these error messages:

```
seqr_1             | Session data corrupted
seqr_1             | 2020-09-21 08:10:36,755 WARNING:  Session data corrupted
```

**Comment by hanars** [comment]
It looks like you upgraded seqr without running the corresponding database migrations. try running the following:
```
docker-compose exec seqr python -m manage makemigrations 
docker-compose exec seqr python -m manage migrate
```

**Comment by bnouyou** [comment]
Thank you so much! This works. I don't have the error messages anymore.

**Comment by bnouyou** [comment]
I have inserted the file with the path of bam files. This time I have no error, it seems that the path is recognized correctly.

But then in the interface, when I click on "show reads", I have "Error loading track data", in the IGV preview: 
![image](https://user-images.githubusercontent.com/22322228/94131024-bc224e80-fe5d-11ea-8b45-985072739dbf.png)

Do you have an idea of this issue ?

Thank you in advance for your help.

**Comment by hanars** [comment]
igvjs and seqr should automatically be using the correct bam and bai file, assuming they are in the same folder with the same file name (i.e /dir/path/my_sample.bam and /dir/path/my_sample.bai)

Assuming you have the correct files, can you send my the logs from the seqr container from when you try to load the bams?

**Comment by bnouyou** [comment]
This is the logs of the container:

```
seqr_1             | [2020-09-24 14:01:57 +0000] [43] [ERROR] Error handling request /api/project/R0001_iop/igv_track/%2Finput_bams%2FEXOME-1%2F19-48742.bwa.sorted.rd.bam.bai
seqr_1             | Traceback (most recent call last):
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
seqr_1             |     self.handle_request(listener, req, client, addr)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 181, in handle_request
seqr_1             |     for item in respiter:
seqr_1             |   File "/seqr/seqr/utils/file_utils.py", line 47, in file_iter
seqr_1             |     for line in f:
seqr_1             |   File "/usr/local/lib/python3.7/codecs.py", line 322, in decode
seqr_1             |     (result, consumed) = self._buffer_decode(data, self.errors, final)
seqr_1             | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 20: invalid continuation byte
seqr_1             | 172.18.8.26 - - [24/Sep/2020:14:01:57 +0000] "GET /api/project/R0001_iop/igv_track/%2Finput_bams%2FEXOME-1%2F19-48742.bwa.sorted.rd.bam.bai HTTP/1.1" 500 0 "-" "-"

```

**Comment by hanars** [comment]
this is a bug, I will try to get a fix up today or tomorrow. Thanks for all your patience on this!

**Comment by hanars** [comment]
Okay, if you update to the latest version of the code again this should be fixed. You shouldn't need to do the migration steps again

**Comment by bnouyou** [comment]
Hello,
I have done the update. But I still have the "Error loading track data" in the IGV viewer.
In the logs, I don't see any error.
```
seqr_1             | Not Found: /media/pedigree_images/pedigree_image_32285504619.png
seqr_1             | 2020-09-28 07:18:46,977 WARNING:  Not Found: /media/pedigree_images/pedigree_image_32285504619.png
seqr_1             | 172.18.8.26 - - [28/Sep/2020:07:18:46 +0000] "GET /media/pedigree_images/pedigree_image_32285504619.png HTTP/1.1" 404 1880 "http://lx165/project/R0001_iop/project_page" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
seqr_1             | 172.18.8.26 - - [28/Sep/2020:07:19:12 +0000] "GET /api/project/R0001_iop/igv_track/%2Finput_bams%2FEXOME-1%2F19-48742.bwa.sorted.rd.bam.bai HTTP/1.1" 200 6673896 "http://lx165/project/R0001_iop/saved_variants/family/F000004_19_48742" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
seqr_1             | 172.18.8.26 - - [28/Sep/2020:07:19:12 +0000] "GET /api/project/R0001_iop/igv_track/%2Finput_bams%2FEXOME-1%2F19-48742.bwa.sorted.rd.bam?someRandomSeed=0.10syrppliskl HTTP/1.1" 206 63578 "http://lx165/project/R0001_iop/saved_variants/family/F000004_19_48742" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
```

**Comment by hanars** [comment]
hmm interesting. Can you open up the chrome browser console and send me the output there?

**Comment by bnouyou** [comment]
Hello,
In the console I see this error:
![image](https://user-images.githubusercontent.com/22322228/94571564-6b9d5d80-0270-11eb-9735-aa74be17a817.png)

And the debugger shows this:
![image](https://user-images.githubusercontent.com/22322228/94572001-d484d580-0270-11eb-92ee-953c227fe9ed.png)
![image](https://user-images.githubusercontent.com/22322228/94572047-df3f6a80-0270-11eb-8b25-104897e3834e.png)

**Comment by hanars** [comment]
@bw2 have you ever encountered that error in IGV js before?

**Comment by bnouyou** [comment]
Maybe I have an idea of the issue. I just tried on another browser Microsoft Edge. And here, I don't have this issue.

So, the problem happens on Chrome and Firefox. Maybe it's because of the version of the browser ?

**Comment by hanars** [comment]
thats possible. In theory, we only support the latest version of chrome

**Comment by bnouyou** [comment]
I have downloaded the latest version of Chrome and Firefox, and I still have this error message in the IGV viewer.
Very strange that I don't have this problem on Edge..
And if I go on https://igv.org/app/ on Chrome and Firefox, it's working too.

**Comment by bw2** [comment]
xhr status 0 is a generic error code.
From https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/status:
"Browsers also report a status of 0 in case of XMLHttpRequest errors."
I'm not sure what the issue is, but it does look like it's at least getting the .bai file successfully since it would only request .bam after parsing the .bai index and figuring out what part of the .bam to request. 
As to why it works in Edge but not in Chrome/Firefox, there might be something wrong with how we're forwarding request/response headers. If there's no workaround, we should try to reproduce the error here.
