### ISSUE TITLE
Unable to assign analysts to cases

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2992]
**Describe the bug**
When clicking the "edit" icon next to Assigned Analyst on the family page, a popup appears requesting an email address. This is usually a type ahead field where you can start typing an analyst name or email address and then select the one you want in a filtered list. The type ahead is no longer appearing. If I enter the full email address manually and click "Submit", I get the "Are you sure you want to add the analyst to this family?" message and click OK, but the Assigned Analyst field remains blank, even after refreshing the page. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F025775_rgp_655 - tried to assign to Emily
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F026452_rgp_435 - tried to assign to Gabrielle

**Scope of the bug**
I have seen this across Rare Genomes Project_Genomes_HMB and _GRU projects.

**Screenshots**

**Comment by hanars** [comment]
this is fixed now

**Comment by Caustint** [comment]
I just tried to assign Stephanie to RGP_929 and am still seeing the same
issue

https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F027700_rgp_929

**Comment by hanars** [comment]
@Caustint can you send me a screenshot of what you see under the "collaborators" section on the RGP project page: https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/project_page

Okay to send in slack if you do not want to share publicly

**Comment by hanars** [comment]
Actually I think I fixed it. Can you try again?

**Comment by Caustint** [comment]
It works! Thanks!

**Comment by Caustint** [comment]
@hanars I was just working on assigning the upcoming RGP callset and successfully assigned 5-10 cases, but am now back to having the same problem as described above. This time I first encountered the issue while trying to assign Ike to RGP_2028 https://seqr.broadinstitute.org/project/R0594_rare_genomes_project_gen/family_page/F032156_rgp_2028

**Comment by hanars** [comment]
Sorry, it looks like I only fixed it in the HMB project but not GRU. You should be all set now
